INSERT INTO `flexi_drives` (`id`, `fichero_listado_hoteles`, `fichero_informacion_ampliada`, `imagen`, `tarifario_FFD`, `created_by`, `dias_antelacion_rese_alta_id`, `dias_antelacion_rese_baja_id`, `created_at`, `updated_at`) VALUES
(1, 'flexidrive/ListadoHoteles.pdf', 'flexidrive/infogeneral.pdf', 'flexidrive/HSFeZWoArFcBeYzQjasL9eDASdQK4loIEjX0KEPv.png', 'flexidrive/e1bEEUnWMEiGWyei9Za5zMuXXeT9cctwPRCA1LHr.xlsx', 'Admin', 15, 10, '2020-08-11 21:13:14', '2020-08-15 02:21:05');

INSERT INTO `flexi_drive_traslations` (`id`, `locale`, `descripcion_general`, `descripcion_hoteles`, `descripcion_autos`, `created_by`, `created_at`, `updated_at`, `flexi_drive_id`) VALUES
(1, 'es', '<p>\r\n            El programa Flexi Fly and Drive establece un mínimo de 6 noches de alojamiento e igual cantidad de días de renta de auto.\r\n            Cada noche de reserva de alojamiento es equivalente a un día renta de auto.\r\n        </p>', '<p><strong>Hoteles:</strong><br>Podrás seleccionar entre más de 100 hoteles en 12 provincias del país.</p>', '<p>\r\n            <strong>Autos:</strong><br>Modelos de autos disponibles para el paquete Flexi, Fly and Drive, varía según la categoría elegida.<br>\r\n            El Programa dispone de 5 categorías (C, E, H, G, y F+) representadas por los siguientes modelos de autos de la compañía Rex.\r\n        </p>', 'Admin', '2020-08-11 21:13:14', '2020-08-15 02:21:06', 1),
(2, 'en', '<p>\r\n            El programa Flexi Fly and Drive establece un mínimo de 6 noches de alojamiento e igual cantidad de días de renta de auto.\r\n            Cada noche de reserva de alojamiento es equivalente a un día renta de auto.\r\n        </p>', '<p>            <strong>Hoteles:</strong><br>Podrás seleccionar entre más de 100 hoteles en 12 provincias del país.</p>', '<p>\r\n            <strong>Autos:</strong><br>Modelos de autos disponibles para el paquete Flexi, Fly and Drive, varía según la categoría elegida.<br>\r\n            El Programa dispone de 5 categorías (C, E, H, G, y F+) representadas por los siguientes modelos de autos de la compañía Rex.\r\n        </p>', 'Admin', '2020-08-11 21:13:14', '2020-08-15 02:21:06', 1),
(3, 'fr', '<p>\r\n            El programa Flexi Fly and Drive establece un mínimo de 6 noches de alojamiento e igual cantidad de días de renta de auto.\r\n            Cada noche de reserva de alojamiento es equivalente a un día renta de auto.\r\n        </p>', '<p>\r\n            <strong>Hoteles:</strong><br>Podrás seleccionar entre más de 100 hoteles en 12 provincias del país.</p>', '<p>\r\n            <strong>Autos:</strong><br>Modelos de autos disponibles para el paquete Flexi, Fly and Drive, varía según la categoría elegida.<br>\r\n            El Programa dispone de 5 categorías (C, E, H, G, y F+) representadas por los siguientes modelos de autos de la compañía Rex.\r\n        </p>', 'Admin', '2020-08-11 21:13:14', '2020-08-15 02:21:06', 1),
(4, 'de', '<p>\r\n            El programa Flexi Fly and Drive establece un mínimo de 6 noches de alojamiento e igual cantidad de días de renta de auto.\r\n            Cada noche de reserva de alojamiento es equivalente a un día renta de auto.\r\n        </p>', '<p><strong>Hoteles:</strong><br>Podrás seleccionar entre más de 100 hoteles en 12 provincias del país.</p>', '<p>\r\n            <strong>Autos:</strong><br>Modelos de autos disponibles para el paquete Flexi, Fly and Drive, varía según la categoría elegida.<br>\r\n            El Programa dispone de 5 categorías (C, E, H, G, y F+) representadas por los siguientes modelos de autos de la compañía Rex.\r\n        </p>', 'Admin', '2020-08-11 21:13:14', '2020-08-15 02:21:06', 1),
(5, 'it', '<p>\r\n            El programa Flexi Fly and Drive establece un mínimo de 6 noches de alojamiento e igual cantidad de días de renta de auto.\r\n            Cada noche de reserva de alojamiento es equivalente a un día renta de auto.\r\n        </p>', '<p>\r\n            <strong>Hoteles:</strong><br>Podrás seleccionar entre más de 100 hoteles en 12 provincias del país.</p>', '<p>\r\n            <strong>Autos:</strong><br>Modelos de autos disponibles para el paquete Flexi, Fly and Drive, varía según la categoría elegida.<br>\r\n            El Programa dispone de 5 categorías (C, E, H, G, y F+) representadas por los siguientes modelos de autos de la compañía Rex.\r\n        </p>', 'Admin', '2020-08-11 21:13:15', '2020-08-15 02:21:06', 1),
(6, 'pt', '<p>\r\n            El programa Flexi Fly and Drive establece un mínimo de 6 noches de alojamiento e igual cantidad de días de renta de auto.\r\n            Cada noche de reserva de alojamiento es equivalente a un día renta de auto.\r\n        </p>', '<p>\r\n            <strong>Hoteles:</strong><br>Podrás seleccionar entre más de 100 hoteles en 12 provincias del país.</p>', '<p>\r\n            <strong>Autos:</strong><br>Modelos de autos disponibles para el paquete Flexi, Fly and Drive, varía según la categoría elegida.<br>\r\n            El Programa dispone de 5 categorías (C, E, H, G, y F+) representadas por los siguientes modelos de autos de la compañía Rex.\r\n        </p>', 'Admin', '2020-08-11 21:13:15', '2020-08-15 02:21:06', 1);
